"""end_date to deadline

Revision ID: 140b7d67e2bc
Revises: 26e6e7f3b659
Create Date: 2025-02-24 17:09:38.399227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '140b7d67e2bc'
down_revision: Union[str, None] = '26e6e7f3b659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('end_date', mysql.DATETIME(), nullable=True))
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###
