"""create tables

Revision ID: 26e6e7f3b659
Revises: ac68cf5a138c
Create Date: 2025-02-10 20:04:59.292619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26e6e7f3b659'
down_revision: Union[str, None] = 'ac68cf5a138c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
